create table notes (
	id INTEGER primary key generated by default as identity,
	name text not null,
	modified TIMESTAMP not null default now(),
	folderId INTEGER references folders(id) on delete cascade not null,
	content text not null
	);